os:
  - osx
language: swift

before_script:
    - brew tap AdoptOpenJDK/openjdk
    - brew cask install adoptopenjdk8
    - brew cask install android-sdk
    - echo "export ANDROID_HOME=/usr/local/share/android-sdk" >> ~/.bash_profile
    - source ~/.bash_profile
    - touch ~/.android/repositories.cfg
    - sdkmanager --update
    - sdkmanager "platform-tools" "platforms;android-28"
    - chmod +x gradlew

script:
    - ./gradlew common:build
    - ./gradlew app:testDebugUnitTest app:assembleDebug


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
