matrix:
    include:
        - language: android
            android:
                components:
                    - tools
                    - platform-tools
                    - build-tools-28.0.3
                    - android-28
                    - extra-android-support
                    - extra-google-m2repository
                    - extra-android-m2repository
            before script:
                - brew tap AdoptOpenJDK/openjdk
                - brew cask install adoptopenjdk8
                - brew cask install android-sdk
                - echo "export ANDROID_HOME=/usr/local/share/android-sdk" >> ~/.bash_profile
                - source ~/.bash_profile
                - touch ~/.android/repositories.cfg
                - export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
                - sdkmanager --update
                - yes | sdkmanager "platform-tools" "platforms;android-28" > /dev/null
                - chmod +x gradlew
            script:
                - ./gradlew common:build --console plain
                - ./gradlew app:testDebugUnitTest app:assembleDebug --console plain
