name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        ./gradlew common:build --console plain
        cd native/KotlinIOS
        xcodebuild \
          -project KotlinIOS.xcodeproj \
          -scheme KotlinIOS \
          -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.4'
    - name: Run tests
      run: |
        ./gradlew common:build --console plain
        cd native/KotlinIOS
        xcodebuild \
          -project KotlinIOS.xcodeproj \
          -scheme KotlinIOS \
          -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.4' \
          test | xcpretty --test --color
