name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 11
    - name: Build
      run: |
        ./gradlew common:build --console plain
        cd native/KotlinIOS
        xcodebuild \
          -project KotlinIOS.xcodeproj \
          -scheme KotlinIOS \
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'
    - name: Run tests
      run: |
        ./gradlew common:build --console plain
        cd native/KotlinIOS
        xcodebuild \
          -project KotlinIOS.xcodeproj \
          -scheme KotlinIOS \
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest' \
          test | xcpretty --test --color
